### ISSUE TITLE
Campaign ID to Facilitate Aggregation of CTA Links to a Livestream, Podcast or Content Event

### ISSUE THREAD

**Issue by mrlynn** [mongodb-developer/mdblinks#15]
I'd like to add a prompt in the creation of Shortlinks called "campaign". This text field will enable creators of shortlinks to group several shortlinks to a single livestream, podcast episode or peice of content. This will facilitate aggregation for visibility into CTA effectiveness for these events.

**Comment by joellord** [comment]
Will be addressed through a process change.
