### ISSUE TITLE
UTM Link Builder generates malformed UTM tags 

### ISSUE THREAD

**Issue by sis0k0** [mongodb-developer/mdblinks#30]
Steps to reproduce:

1. Navigate to **UTM Link Builder** from the side menu.
2. Write something in the **Medium** input field.
3. Observe the generated link: `?utm_campaign=devrel&utm_medium=%5Bobject%20Object%5D&utm_term=stanimira.vlaeva`

The same thing happens with the **Source** input and none of the other inputs.

**Comment by sis0k0** [comment]
Found the culprit - https://github.com/mongodb-developer/mdblinks/blob/178e3bd1643069cdde004ee785ab62cd239fdc30/admin/src/pages/UTMBuilder.js#L107. I'll make a PR later or on Monday.

**Comment by joellord** [comment]
Fixed in version 2.1.1
